[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.0.0"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.10.0"

[[constraint]]
  name = "github.com/pressly/goose"
  version = "2.4.5"

[[constraint]]
  name = "github.com/ziutek/mymysql"
  version = "1.5.4"

[prune]
  go-tests = true
  unused-packages = true
